# Generated by Django 4.1.7 on 2023-10-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_store_data_service_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeCommercial_data',
        ),
        migrations.DeleteModel(
            name='IncomeConsumption_data',
        ),
        migrations.DeleteModel(
            name='Test_data',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.RemoveField(
            model_name='apart_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='apart_data',
            name='commercial_code',
        ),
        migrations.RemoveField(
            model_name='apart_data',
            name='commercial_name',
        ),
        migrations.RemoveField(
            model_name='apart_data',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='population_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='population_data',
            name='commercial_code',
        ),
        migrations.RemoveField(
            model_name='population_data',
            name='commercial_name',
        ),
        migrations.RemoveField(
            model_name='population_data',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='sales_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sales_data',
            name='commercial_code',
        ),
        migrations.RemoveField(
            model_name='sales_data',
            name='commercial_name',
        ),
        migrations.RemoveField(
            model_name='sales_data',
            name='nation',
        ),
        migrations.AddField(
            model_name='apart_data',
            name='commercial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.commercial_data'),
        ),
        migrations.AddField(
            model_name='population_data',
            name='commercial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.commercial_data'),
        ),
        migrations.AddField(
            model_name='sales_data',
            name='commercial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.commercial_data'),
        ),
    ]
