# Generated by Django 4.1.7 on 2023-10-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_apart_data_averge_apart_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apart_data',
            old_name='averge_apart_price1',
            new_name='averge_apart_price',
        ),
    ]
