# Generated by Django 4.1.7 on 2023-10-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_changecommercial_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart_data',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commercial_data'),
        ),
        migrations.AlterField(
            model_name='population_data',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commercial_data'),
        ),
        migrations.AlterField(
            model_name='sales_data',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commercial_data'),
        ),
    ]
