version: '3'
services:
  market:
    build:
      context:  /home/hadoop/mseo/location/market/mysite
    image: market
    ports:
      - "8880:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
    volumes:
      - /home/hadoop/mseo/location/market/mysite:/srv/market
    networks:
      - mynetwork

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - TZ=Asia/Seoul
    ports:
      - "5672:5672
      - "15672:15672"
    expose:
      - "15672"
    networks:
      - mynetwork

  celery_beat:
    restart: always
    build:
      context: /home/hadoop/mseo/location/market/mysite
    command: "celery -A mysite beat --loglevel=info"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq
      - market
      - celery_worker
    networks:
      - mynetwork

  celery_worker:
    restart: always
    build:
      context: /home/hadoop/mseo/location/market/mysite
    command: "celery -A mysite worker --loglevel=info"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    volumes:
      - /home/hadoop/mseo/location/market/mysite:/srv/market
    depends_on:
      - market
      - rabbitmq
    networks:
      - mynetwork

  flower:
      image: mher/flower
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
        - FLOWER_PORT=5555
      ports:
        - 5555:5555
      networks:
        - mynetwork

networks:
  mynetwork:
    external:
      name: mynetwork
