version: '3'
services:
  flower:
      image: mher/flower
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
        - FLOWER_PORT=5555
      ports:
        - 5555:5555
      networks:
        - mynetwork
networks:
  mynetwork:
    external:
      name: mynetwork