from django.db import models

# Create your models here.

class Commercial_data(models.Model):
    nation = models.CharField(max_length=8, default='')
    city = models.CharField(max_length=8, default='')
    commercial_code = models.IntegerField(default=0)
    commercial_name = models.CharField(max_length=30, default='')
    x = models.IntegerField(default=0)
    y = models.IntegerField(default=0)
    county_code = models.IntegerField(default=0)
    administrative_code = models.IntegerField(default=0)

class Store_data(models.Model):
    commercial = models.ForeignKey(Commercial_data, on_delete=models.CASCADE)
    year = models.IntegerField(default=0)
    quarter = models.IntegerField(default=0)
    service_code = models.CharField(max_length=20, blank=True, null=True)
    service_name = models.CharField(max_length=20, blank=True, null=True)
    store_num = models.IntegerField(default=0)
    similar_store_num = models.IntegerField(default=0)
    opening_rate = models.IntegerField(default=0)
    opening_store_num = models.IntegerField(default=0)
    closure_rate = models.IntegerField(default=0)
    closure_store_num = models.IntegerField(default=0)
    franchisee_store_num = models.IntegerField(default=0)

class Revenue_data(models.Model):
    commercial = models.ForeignKey(Commercial_data, on_delete=models.CASCADE)
    year=models.IntegerField(default=0)
    quarter=models.IntegerField(default=0)
    service_code=models.CharField(max_length=20, default='')
    service_name=models.CharField(max_length=20, default='')
    quarterly_sales=models.BigIntegerField(default=0)
    quarterly_sales_num=models.BigIntegerField(default=0)
    weekday_sales_ratio=models.BigIntegerField(default=0)
    weekend_sales_ratio=models.BigIntegerField(default=0)
    monday_sales_ratio=models.BigIntegerField(default=0)
    tuesday_sales_ratio=models.BigIntegerField(default=0)
    wednesday_sales_ratio=models.BigIntegerField(default=0)
    thursday_sales_ratio=models.BigIntegerField(default=0)
    friday_sales_ratio=models.BigIntegerField(default=0)
    saturday_sales_ratio=models.BigIntegerField(default=0)
    sunday_sales_ratio=models.BigIntegerField(default=0)
    time00_06_sales_ratio=models.BigIntegerField(default=0)
    time06_11_sales_ratio=models.BigIntegerField(default=0)
    time11_14_sales_ratio=models.BigIntegerField(default=0)
    time14_17_sales_ratio=models.BigIntegerField(default=0)
    time17_21_sales_ratio=models.BigIntegerField(default=0)
    time21_24_sales_ratio=models.BigIntegerField(default=0)
    male_sales_ratio=models.BigIntegerField(default=0)
    female_sales_ratio=models.BigIntegerField(default=0)
    age10_sales_ratio=models.BigIntegerField(default=0)
    age20_sales_ratio=models.BigIntegerField(default=0)
    age30_sales_ratio=models.BigIntegerField(default=0)
    age40_sales_ratio=models.BigIntegerField(default=0)
    age50_sales_ratio=models.BigIntegerField(default=0)
    age60_sales_ratio=models.BigIntegerField(default=0)
    weekday_sales_amount=models.BigIntegerField(default=0)
    weekend_sales_amount=models.BigIntegerField(default=0)
    monday_sales_amount=models.BigIntegerField(default=0)
    tuesday_sales_amount=models.BigIntegerField(default=0)
    wednesday_sales_amount=models.BigIntegerField(default=0)
    thursday_sales_amount=models.BigIntegerField(default=0)
    friday_sales_amount=models.BigIntegerField(default=0)
    saturday_sales_amount=models.BigIntegerField(default=0)
    sunday_sales_amount=models.BigIntegerField(default=0)
    time00_06_sales_amount=models.BigIntegerField(default=0)
    time06_11_sales_amount=models.BigIntegerField(default=0)
    time11_14_sales_amount=models.BigIntegerField(default=0)
    time14_17_sales_amount=models.BigIntegerField(default=0)
    time17_21_sales_amount=models.BigIntegerField(default=0)
    time21_24_sales_amount=models.BigIntegerField(default=0)
    male_sales_amount=models.BigIntegerField(default=0)
    female_sales_amount=models.BigIntegerField(default=0)
    age10_sales_amount=models.BigIntegerField(default=0)
    age20_sales_amount=models.BigIntegerField(default=0)
    age30_sales_amount=models.BigIntegerField(default=0)
    age40_sales_amount=models.BigIntegerField(default=0)
    age50_sales_amount=models.BigIntegerField(default=0)
    age60_sales_amount=models.BigIntegerField(default=0)
    weekday_sales_num=models.BigIntegerField(default=0)
    weekend_sales_num=models.BigIntegerField(default=0)
    monday_sales_num=models.BigIntegerField(default=0)
    tuesday_sales_num=models.BigIntegerField(default=0)
    wednesday_sales_num=models.BigIntegerField(default=0)
    thursday_sales_num=models.BigIntegerField(default=0)
    friday_sales_num=models.BigIntegerField(default=0)
    saturday_sales_num=models.BigIntegerField(default=0)
    sunday_sales_num=models.BigIntegerField(default=0)
    time_06_sales_num=models.BigIntegerField(default=0)
    time_11_sales_num=models.BigIntegerField(default=0)
    time_14_sales_num=models.BigIntegerField(default=0)
    time_17_sales_num=models.BigIntegerField(default=0)
    time_21_sales_num=models.BigIntegerField(default=0)
    time_24_sales_num=models.BigIntegerField(default=0)
    male_sales_num=models.BigIntegerField(default=0)
    female_sales_num=models.BigIntegerField(default=0)
    age10_sales_num=models.BigIntegerField(default=0)
    age20_sales_num=models.BigIntegerField(default=0)
    age30_sales_num=models.BigIntegerField(default=0)
    age40_sales_num=models.BigIntegerField(default=0)
    age50_sales_num=models.BigIntegerField(default=0)
    age60_sales_num=models.BigIntegerField(default=0)
    num=models.BigIntegerField(default=0)

class Apart_data(models.Model):
    commercial = models.ForeignKey(Commercial_data, on_delete=models.CASCADE)
    year=models.IntegerField(default=0)
    quarter=models.IntegerField(default=0)
    apart_num=models.IntegerField(default=0)
    apart_1underprice=models.IntegerField(default=0)
    apart_1price=models.IntegerField(default=0)
    apart_2price=models.IntegerField(default=0)
    apart_3price=models.IntegerField(default=0)
    apart_4price=models.IntegerField(default=0)
    apart_5price=models.IntegerField(default=0)
    apart_6price=models.IntegerField(default=0)
    averge_apart_price=models.BigIntegerField(default=0)

class Population_data(models.Model):
    commercial = models.ForeignKey(Commercial_data, on_delete=models.CASCADE)
    year=models.IntegerField(default=0)
    quarter=models.IntegerField(default=0)
    total_population=models.IntegerField(default=0)
    male_population=models.IntegerField(default=0)
    female_population=models.IntegerField(default=0)
    age10_population=models.IntegerField(default=0)
    age20_population=models.IntegerField(default=0)
    age30_population=models.IntegerField(default=0)
    age40_population=models.IntegerField(default=0)
    age50_population=models.IntegerField(default=0)
    age60_population=models.IntegerField(default=0)
    time_1_population=models.IntegerField(default=0)
    time_2_population=models.IntegerField(default=0)
    time_3_population=models.IntegerField(default=0)
    time_4_population=models.IntegerField(default=0)
    time_5_population=models.IntegerField(default=0)
    time_6_population=models.IntegerField(default=0)
    monday_population=models.IntegerField(default=0)
    tuesday_population=models.IntegerField(default=0)
    wednesday_population=models.IntegerField(default=0)
    thursday_population=models.IntegerField(default=0)
    friday_population=models.IntegerField(default=0)
    saturday_population=models.IntegerField(default=0)
    sunday_population=models.IntegerField(default=0)
